locomotion_task:

    initial_base_lin: [0., 0., 0.766, 0., 0., 0.]
    initial_base_ang: [0., 0., 0., 0., 0., 0.]

    # Left Foot: 0, Right Foot: 1
    initial_ee_motion_lin:
        0: [0.003, 0.111, 0.]
        1: [0.003, -0.111, 0.]
    initial_ee_motion_ang:
        0: [0., 0., 0.]
        1: [0., 0., 0.]

    final_base_lin: [0.1, 0.0, 0.766, 0., 0., 0.]
    final_base_ang: [0., 0., 0., 0., 0., 0.]

    terrain_type: "flat_ground"

locomotion_param:

    duration_base_polynomial: 0.1
    force_polynomials_per_stance_phase: 3
    ee_polynomials_per_swing_phase: 2
    force_limit_in_normal_direction: 1000.
    dt_constraint_range_of_motion: 0.08
    dt_constraint_dynamic: 0.1
    dt_constraint_base_motion: 0.025
    b_optimize_timings: false
    bound_phase_duration: [0.45, 1.65]

    ee_phase_durations:
        0: [0.45, 0.75, 1.65]
        1: [2.85]
    ee_in_contact_at_start:
        0: True
        1: True

    costs:
        w_FinalBaseLinPosCost: [2., 2., 2.]
        w_FinalBaseLinVelCost: [1., 1., 1.]
        w_FinalBaseAngPosCost: [2., 2., 2.]
        w_FinalBaseAngVelCost: [1., 1., 1.]
        w_FinalEEMotionLinPosCost: [2., 2., 2.]
        w_FinalEEMotionAngPosCost: [2., 2., 2.]
        w_IntermediateBaseLinVelCost: [0.001, 0.001, 1.0]
        w_IntermediateBaseAngVelCost: [0.01, 0.01, 0.01]
        w_BaseLinVelDiffCost: [0.1, 0.1, 1.0]
        w_BaseAngVelDiffCost: [0.1, 0.1, 0.1]
        w_WrenchLinPosCost: [0.1, 0.1, 0.01]
        w_WrenchAngPosCost: [0.1, 0.1, 0.01]
        w_WrenchLinVelCost: [0.01, 0.01, 0.01]
        w_WrenchAngVelCost: [0.01, 0.01, 0.01]
        w_WrenchLinVelDiffCost: [0.001, 0.001, 0.001]
        w_WrenchAngVelDiffCost: [0.001, 0.001, 0.001]
